from dataclasses import dataclass, field
from typing import List, Optional

from agno.models.message import Message


@dataclass
class RunMessages:
    """Container for messages used in an Agent run.

    Attributes:
        messages: List of all messages to send to the model
        system_message: The system message for this run
        user_message: The user message for this run
        extra_messages: Extra messages added after the system and user messages
        output_model_messages: List of messages generated by output_model (separate from main model)
        reasoning_model_messages: List of messages generated by reasoning_model (separate from main model)
        parser_model_messages: List of messages generated by parser_model (separate from main model)
        memory_model_messages: List of messages generated by memory_manager model (separate from main model)
        session_summary_model_messages: List of messages generated by session_summary_manager model (separate from main model)
        compression_model_messages: List of messages generated by compression_manager model (separate from main model)
        culture_model_messages: List of messages generated by culture_manager model (separate from main model)
    """

    messages: List[Message] = field(default_factory=list)
    system_message: Optional[Message] = None
    user_message: Optional[Message] = None
    extra_messages: Optional[List[Message]] = None
    output_model_messages: List[Message] = field(default_factory=list)
    reasoning_model_messages: List[Message] = field(default_factory=list)
    parser_model_messages: List[Message] = field(default_factory=list)
    memory_model_messages: List[Message] = field(default_factory=list)
    session_summary_model_messages: List[Message] = field(default_factory=list)
    compression_model_messages: List[Message] = field(default_factory=list)
    culture_model_messages: List[Message] = field(default_factory=list)

    def get_input_messages(self) -> List[Message]:
        """Get the input messages for the model."""
        input_messages = []
        if self.system_message is not None:
            input_messages.append(self.system_message)
        if self.user_message is not None:
            input_messages.append(self.user_message)
        if self.extra_messages is not None:
            input_messages.extend(self.extra_messages)
        return input_messages
